### ISSUE TITLE
get_children in psutil is now children

### ISSUE THREAD

**Issue by dclark87** [pythonprofilers/memory_profiler#101]
Per the psutil documentation in http://pythonhosted.org/psutil/#psutil.Process.children, the iteration in https://github.com/fabianp/memory_profiler/blob/master/memory_profiler.py#L54 should actually be:

for p in process.children(recursive=True):

Otherwise you get an Exception:
AttributeError: 'Process' object has no attribute 'get_children'

**Comment by fabianp** [comment]
Thanks for the report!. I've attempted a fix in 0e53367. Does it look fine ?

**Comment by dclark87** [comment]
Yep looks good!

**Comment by Juanlu001** [comment]
This can probably be closed.
