### ISSUE TITLE
Can the plot be scaled to show fine detail?

### ISSUE THREAD

**Issue by pbowyer** [pythonprofilers/memory_profiler#103]
I have an issue with making the plot from a `mprof` run legible. This is how mine looks:
 ![plot](https://cloud.githubusercontent.com/assets/89852/10689027/235c2cc4-7970-11e5-9d83-2a05599857dc.png)

I'd like to be able to stretch/zoom the plot - make it much larger, so the function markers don't overlap.

I have tried changing matplotlib's `savefig.dpi` and `figure.figsize` values, and both result in the graph being scaled, rather than the canvas being larger and the line/function markers becoming thinner and separated, and the text smaller.

I tried a really wide figure using these settings in my `matplotlibrc`:

```
figure.figsize   : 200, 10    # figure size in inches
savefig.dpi      : 100
```

but it still plotted at 1400x600.

Do you know a way to make this possible?

**Comment by fabianp** [comment]
Hi!

The code that creates the figure is here:

   https://github.com/fabianp/memory_profiler/blob/master/mprof#L454

Right now the figsize is hard-coded but it would totally make sense to be able to set it via a command line option. Would that solve your problem?

**Comment by pbowyer** [comment]
I gave it a test by doubling the width on [Line 454](https://github.com/fabianp/memory_profiler/blob/master/mprof#L454) - unfortunately it stretches the markers:
![plot](https://cloud.githubusercontent.com/assets/89852/10690300/b2537358-7978-11e5-9fa1-54da8da1d777.png)

**Comment by fabianp** [comment]
I see. What you would like is to have the legend outside the plot, right?

**Comment by fabianp** [comment]
I pushed a fix that moves the legend out. I see things like this, tell me if that fixes it for you.

![figure_1](https://cloud.githubusercontent.com/assets/277639/10691807/7242f78e-798c-11e5-84ae-7868452a614e.png)

**Comment by pbowyer** [comment]
> I see. What you would like is to have the legend outside the plot, right?

Not quite :)  I'd like to be able to make the graph much bigger, so that all the function bracketing between 150-250 seconds on the graph don't overlap, and I can make out what's going on. I don't mind if the graph is 10000px wide to do this.

Currently if I change the graph size, it scales everything: line thickness, size of function bracket, size of text. I'd like the canvas size to be independent of these features, so I can "zoom in" on the PNG and see what's going on.

**Comment by fabianp** [comment]
I see. Unfortunately my matplotlib knowledge is limited ... do you have an idea of what matplotlib code could give you what you are looking for?

**Comment by pbowyer** [comment]
No, my knowledge is limited too - I will try and find out.

**Comment by fabianp** [comment]
Cool, thanks. If you find a solution, please tell me :-)

**Comment by pgervais** [comment]
@pbowyer: what you want is change the height_ratio here: https://github.com/fabianp/memory_profiler/blob/master/mprof#L258

Brackets are drawn as lines and they scale like the axis instead of having a constant size. There must be a way of doing the latter but I haven't spent enough time to find it. A stop gap would be to pass the aspect ratio as a parameter to `mprof`.

Hope this help...

**Comment by pgervais** [comment]
Ahem. `height_ratio` determines the height of the bracket relative to the vertical axis. But my point this holds.

**Comment by Juanlu001** [comment]
Unsure whether this can be closed?

**Comment by Juanlu001** [comment]
I assume #105 addressed this, so I'm closing.
