### ISSUE TITLE
Bug in include_children loop

### ISSUE THREAD

**Issue by dclark87** [pythonprofilers/memory_profiler#107]
At https://github.com/fabianp/memory_profiler/blob/master/memory_profiler.py#L66 and https://github.com/fabianp/memory_profiler/blob/master/memory_profiler.py#L70 the line:

mem += getattr(process, meminfo_attr)()[0] / _TWO_20

should be replaced with

mem += getattr(p, meminfo_attr)()[0] / _TWO_20

So the p as the child process iterable in the for loop has its memory captured, instead of just the parent process.

**Comment by florentx** [comment]
Proposed PR #109

**Comment by Juanlu001** [comment]
https://github.com/pythonprofilers/memory_profiler/pull/109 was merged so probably this can be closed.
