### ISSUE TITLE
'Process' object has no attribute 'get_memory_info'

### ISSUE THREAD

**Issue by hanlequantum** [pythonprofilers/memory_profiler#114]
It seems the same problem with #94
version: psutil 4.1.0; memory_profiler 0.4.1
 I use others code:
![screen shot 2016-04-07 at 2 46 52 pm](https://cloud.githubusercontent.com/assets/16998655/14362925/c03e8b4e-fccf-11e5-9c9b-4b87fa91857c.jpg)
run "memory_usage_psutil() " and get:
![screen shot 2016-04-07 at 2 47 14 pm](https://cloud.githubusercontent.com/assets/16998655/14362949/d2dfc72c-fccf-11e5-925c-e55d6572abb5.jpg)

**Comment by hanlequantum** [comment]
while I checked memory_info() instead of get_memory_info() and it works.
Could you let others know?

**Comment by fabianp** [comment]
Thanks for the report. Not sure I understand, is there something to be fixed on my side?

**Comment by hanlequantum** [comment]
No need to fix. However, I have a problem about "memory_usage". I'd like to know the memory usage of a function with 4 arguments: f (a,b,c,d). I'm a beginner of python and I have no idea what kw in (f, args, kw) is. How to deal with 4 args? The following picture includes a 2 args example.
![screen shot 2016-04-08 at 10 54 11 am](https://cloud.githubusercontent.com/assets/16998655/14387640/5c3d66f2-fd78-11e5-8f85-0d98756f98b8.jpg)

**Comment by fabianp** [comment]
if you want to call f(a, b, c, d) you should call it as

    args = (a, b, c, d)
    memory_usage((f, args))

Hope that helps

**Comment by xwsoul** [comment]
When I using `apt-get` to install the `memory_profiler` under the Ubuntu 16.04 server,  it raised this error.
I try to install `memory_profiler` by using `pip`, the problem resolved.

**Comment by Juanlu001** [comment]
This probably can be closed.
