### ISSUE TITLE
memory usage in "for loop" is not detailed enough

### ISSUE THREAD

**Issue by Sovetnikov** [pythonprofilers/memory_profiler#122]
At start, i want to thank you for this tool.

And now about the issue.

Test code:

```
from memory_profiler import profile

def gen(count):
    r = list(range(0,count))
    return r

_global_var = None
def _gen_cache():
    global _global_var
    if not _global_var:
        _global_var = gen(10*1024*1024)

@profile(precision=4)
def test():
    a = gen(90000)
    for i in range(0,10):
        b = i
        _gen_cache()
        g = i

if __name__ == "__main__":
    test()
```

Profiler output:

```
Line #    Mem usage    Increment   Line Contents
================================================
    13  10.4336 MiB   0.0000 MiB   @profile(precision=4)
    14                             def test():
    15  12.1445 MiB   1.7109 MiB       a = gen(90000)
    16 213.4453 MiB 201.3008 MiB       for i in range(0,10):
    17 213.4453 MiB   0.0000 MiB           b = i
    18 213.4453 MiB   0.0000 MiB           _gen_cache()
    19 213.4453 MiB   0.0000 MiB           g = i
```

You see the problem - information about memory allocation in _gen_cache() got lost.
I see in sources that problem is that trace function stores only total memory on every code line executed, but not memory delta between line executions.

In my opinion resulting output must be something like that:

```
Line #    Mem usage    Increment   Line Contents
================================================
    13  10.4141 MiB  10.4141 MiB   @profile(precision=4)
    14                             def test():
    15  12.1328 MiB   1.7188 MiB       a = gen(90000)
    16 213.4141 MiB   0.0000 MiB       for i in range(0,10):
    17 213.4141 MiB   0.0000 MiB           b = i
    18 213.4141 MiB 201.2812 MiB           _gen_cache()
    19 213.4141 MiB   0.0000 MiB           g = i
```

In attachment is my modified version of memory_profiler that works by calculating memory deltas (it's insufficiently tested but works).

[memory_profiler.txt](https://github.com/fabianp/memory_profiler/files/504397/memory_profiler.txt)

**Comment by fabianp** [comment]
Hey,

indeed, the way memory is handled inside for loops is not good at all. Could you please submit your code as a pull request against master? Otherwise its difficult to see the changes you made.

Thanks!

**Comment by Sovetnikov** [comment]
Here it is https://github.com/fabianp/memory_profiler/pull/123

**Comment by Juanlu001** [comment]
this was closed in https://github.com/pythonprofilers/memory_profiler/pull/166!
