### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 4327: ordinal not in range(128)

### ISSUE THREAD

**Issue by today4king** [pythonprofilers/memory_profiler#127]
Python 35, memory_profile0.41
In my case change line #911 worked
from:
with open(filename) as f:
to:
with open(filename,'rt',encoding='utf-8') as f:

**Comment by superbobry** [comment]
Thanks, `open` defaults to the default locale encoding, so the error could only happen if you have something other than UTF in `LC_LANG`, e.g. `LC_LANG=C`. Is my assumption correct?

**Comment by janissl** [comment]
This is a typical issue on Windows when open() has been called without an explicitly set encoding value and the current default locale is other than English. Unfortunately, it is impossible to set locales to use the UTF-8 encoding on Windows. The only solution is what today4king's has proposed.

**Comment by Andrej730** [comment]
Seems like it's still an issue.

https://github.com/pythonprofilers/memory_profiler/blob/d986422bef66a132ecb7e0270caeb7ec16a1d2c3/memory_profiler.py#L1174

**Comment by fabianp** [comment]
I'm hesitant to apply this solution as it hard codes the fact that the file you want to open is utf8. What would happen if it's in a different encoding?

Also, please report your Python version and OS when commenting

**Comment by Andrej730** [comment]
If you open file in windows 1251 with cyrillic characters using `open('file', 'r', encoding='utf-8').read()` you'll get:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 0: invalid continuation byte`

From my own experience if you're using cyrillic characters in script files you tend to use utf-8 to avoid errors. So it's just more possible that python file will be in utf-8 and you won't get the error.
