### ISSUE TITLE
Pydev error:

### ISSUE THREAD

**Issue by katie-simmons** [pythonprofilers/memory_profiler#135]
Thanks for building and maintaining memory_builder - it's proving a really useful module for me right now. I just wanted to let you know that I received the following error while debugging my own app that uses memory_profiler in PyCharm 2016.3.3 (Build #PY-163.15188.4):

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
[http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html](http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html)
to see how to restore the debug tracing back correctly.
Call Location:
File "<my_project_path>/venv/lib/python2.7/site-packages/memory_profiler.py, line 729, in enable
    sys.settrace(self.trace_memory_usage)

The [blog post](http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html) linked was helpful if you'd like to take a look. Let me know if I can provide any further info - this is more of a heads-up than anything, as I was able to comment out a few lines and still use memory_profiler. Thanks again for the hard work! 😀

**Comment by fabianp** [comment]
Thanks for the heads up. memory_profiler indeed uses sys.settrace() to get the memory consumption -- but to the best of my knowledge there's not an easy way around it.

**Comment by Juanlu001** [comment]
This problem also appears with PyCharm and other tools that use `sys.settrace()`, see for instance https://github.com/pytest-dev/pytest-cov/issues/131. This is a known problem but nothing can be done about it, so I'd rather close this.
