### ISSUE TITLE
understanding memory units and --with-children

### ISSUE THREAD

**Issue by tendres** [pythonprofilers/memory_profiler#151]
Hi,
I am working on an ubuntu server with 64GB of RAM.
I have been trying to debug a memory leak by running our problem script on our server and pulling the .dat file to my OS X machine to plot.
With a straight mprof run the plot does not reflect the slow memory creep I am seeing via htop - so I am assuming the leak is not in the main thread.
When I run the same using '--with-children' and plot the results, peak memory usage is labeled at over 200,000 MiB(!) and the plot (more like a square wave) does not reflect the slow climb as witnessed in htop.
Suggestions or help in understanding appreciated. Thanks!

**Comment by fabianp** [comment]
Don't know what to say. Perhaps the burst of memory is too fast for mprof to find it? You can play with a lower value of the --interval option, e.g.,

mprof run --interval=0.01 your_script.py

**Comment by Juanlu001** [comment]
Without more info to reproduce this, I'm closing the issue - if you can provide a [short, self-contained, correct example](http://sscce.org/) that showcases the problem, we might reopen it.
