### ISSUE TITLE
Getting an error when trying to use 'mprof'

### ISSUE THREAD

**Issue by jashnani** [pythonprofilers/memory_profiler#153]
I get a runtime error when I try to use 'mprof' in the following way:
>>python mprof run myfile.py

RuntimeError: There is no access to source file of the profiled function

But it continues to run my python script even after mprof has exited.

**Comment by jashnani** [comment]
I installed psutil and the error went away. Can we improve error reporting for this?

**Comment by fabianp** [comment]
Not sure why psutils solves this. In any case, the right way is to run it without python, i.e.,

    mprof run myfile.py

In any case, patches on reporting this are welcome.
