### ISSUE TITLE
unable to use mprof in windows 10, prompts 'How do you want to open this file?'

### ISSUE THREAD

**Issue by BurakaKrishna** [pythonprofilers/memory_profiler#156]
Tried running the mprof command line helper for multiprocessing example, but output given is 'How do you want to open this file'pop up text file,anybody has experienced it before,any help would be great

**Comment by BurakaKrishna** [comment]
Got clarified from issue #75 
 If .py extension is added, and also a .bat file added with the following contents then the installation will work as intended under windows.

@echo off
python "%~dpn0.py" %*

**Comment by fabianp** [comment]
Do you think there's something that  memory profiler should do differently?

**Comment by BurakaKrishna** [comment]
After doing the above,memory profiler is working perfectly.
But,if installation procedure, adds a .py file containing mprof script and a bat file with the above contents,it will be great.

**Comment by fabianp** [comment]
Could you submit a pull request implementing this bat file please?

Thanks

**Comment by BurakaKrishna** [comment]
Yes, I will try to implement the bat file, and submit a pull request

**Comment by dofine** [comment]
Same problem here for me. Waiting for @BurakaKrishna pull. Thanks !

**Comment by Juanlu001** [comment]
For anybody subscribing to this issue, latest development version of memory_profiler gained better support on Windows. Please check it out and tell us what you think.
