### ISSUE TITLE
recording timestamps in imported file with @profile

### ISSUE THREAD

**Issue by RobinRamael** [pythonprofilers/memory_profiler#173]
It says in the documentation that 'If your Python file imports the memory profiler from memory_profiler import profile these timestamps will not be recorded. Comment out the import, leave your functions decorated, and re-run.' 

I'm profiling a script that imports another file that contains the function to profile and commenting out the `from memory_profiler import profile` line in that file just makes `mprof run` crash with an `ImportError`.

Is this use case supported?

**Comment by bernizt** [comment]
Could you please try if #175 fixes your issue? You should be able to profile your python script with:

`mprof run --python <script>`

**Comment by RobinRamael** [comment]
My apologies for taking so long to reply. The PR fixes my issue! Thanks!

**Comment by Juanlu001** [comment]
#175 was not merged but @fabianp already fixed the issue (see discussion there), so I'm going to close this - please comment if the problem appears again!

**Comment by gee4vee** [comment]
I am running as required without the import statement but I see two things happening:

1) I no longer see it print out the line-by-line memory usage. Is that expected?
2) The plot does not yet show the function names on the side with their execution times. The run is still ongoing so I'm not sure if those are added at the end or not. If I run `mprof plot` with the .dat file as it is now I don't see the function names and brackets. Is that expected? Will they get added at the end?

**Comment by DarthThomas** [comment]
> I am running as required without the import statement but I see two things happening:
> 
> 1. I no longer see it print out the line-by-line memory usage. Is that expected?
> 2. The plot does not yet show the function names on the side with their execution times. The run is still ongoing so I'm not sure if those are added at the end or not. If I run `mprof plot` with the .dat file as it is now I don't see the function names and brackets. Is that expected? Will they get added at the end?

Hey, I also don't see the function names and brackets. Did you find out why?
