### ISSUE TITLE
mprof run script with command line arguments

### ISSUE THREAD

**Issue by aleksiy325** [pythonprofilers/memory_profiler#176]
When using the `mprof run <script>` syntax its not possible to use command line arguments for the process as mprof interprets them instead. My current workaround is to modify `p = subprocess.Popen(program)` to use ` shell=True` and pass the script arg as a string with additional arguments. Maybe adding an command line option for using `shell=True` would be useful?

**Comment by Juanlu001** [comment]
Thanks for the report @aleksiy325. Do you mean that the options listed here https://github.com/pythonprofilers/memory_profiler/blob/f36ef23/mprof#L180-L189 are not being read? Can you give a specific example of what you're trying to achieve and the diff that you're using?

**Comment by aleksiy325** [comment]
@Juanlu001  Huh I just tried it again and it seems to work.  To clarify my original statement though I was having trouble profiling a script that also took in arguments. `mprof run -M python <script> --script-arg` as mprof seemed to try and interpret the --script-arg. My mistake.
