### ISSUE TITLE
Command line arguments meant for profiled script are being rejected by mprof

### ISSUE THREAD

**Issue by axlan** [pythonprofilers/memory_profiler#179]
This seems to be another case like https://github.com/pythonprofilers/memory_profiler/issues/176

For example:
`prof run python gnss_analysis/tools/fetch_hitl_metrics.py --build_file tmp/build-list-latest.csv --n_days_master 10`
Gives the error:
```
usage: mprof run [options] program
mprof: error: unrecognized arguments: --build_file tmp/build-list-latest.csv --n_days_master 10
```
I'm running memory-profiler==0.50.0 with Python 2.7.14

**Comment by Cuky88** [comment]
Same Problem here. 
`mprof run -M python3 main.py -s GlobalSettings/testSimMulti`
returns:
`usage: mprof run [options] program
mprof: error: unrecognized arguments: -s GlobalSettings/testSimMulti`

**Comment by JaimieMurdock** [comment]
I'm having this problem with Python 3.6.1.

**Comment by axlan** [comment]
It looks like the coded is currently not set up to support passing args to the profiled script. I added a PR to add this feature and clarify the command line usage.

**Comment by nikanar** [comment]
I still have this problem, is it because the latest change is not yet pushed to pip ?

**Comment by fabianp** [comment]
I just uploaded a new version to pypi. Please let me know if the problem persists.

**Comment by hnykda** [comment]
It works!
