### ISSUE TITLE
@profile decorator does not work on two or more flask routes

### ISSUE THREAD

**Issue by spacether** [pythonprofilers/memory_profiler#186]
When one tries to use @profile on two or more flask routes/functions this error is thrown:

`AssertionError: View function mapping is overwriting an existing endpoint function: wrapper
`
The solution is to use @wraps in the decorator definition.
Can we add @wraps in the profile decorator definition?
I posted a stack-overflow question and solution here:
https://stackoverflow.com/questions/48193461/use-memory-profiler-to-profile-lines-in-a-flask-app/48193527#48193527

**Comment by Juanlu001** [comment]
Looks reasonable, would you please make a pull request for that? Please add one more to the queue :)

**Comment by spacether** [comment]
The above merged PR fixes this issue, the below code runs successfully.
```
from memory_profiler import profile
from flask import Flask
app = Flask(__name__)

@app.route("/one")
@profile
def one():
    return "Hello one!"


@app.route("/two")
@profile
def two():
    return "Hello two!"
```
I am closing this issue, thanks for the PR merge!

**Comment by Juanlu001** [comment]
Thanks to you for doing the work @spacether! :)

**Comment by willjhenry** [comment]
Same error for 0.58.0. The source that pip installs does not match the source on github.
