### ISSUE TITLE
mprof disables usage of __file__

### ISSUE THREAD

**Issue by matus-stehlik** [pythonprofilers/memory_profiler#196]
When running any script with `mprof` the `__file__` in profiled program is always is path to `memory_profiler.py`.

## Example

Lets say that you profile script that reads some data file from relative location specified using `__file__`

```
# script_to_profile.py
import os
data_path = os.path.join(os.path.dirname(__file__), data.csv)
print(data_path)
```

executing this as `python <path/to/script/>script_to_profile.py` 
prints `<path/to/script/>data.csv`

however, running `mprof run <path/to/script/>script_to_profile.py`
prints `<path/to/site-packages/>data.csv`

this makes it impossible to profile scripts that rely on specifying paths to static files using __file__

**Comment by fabianp** [comment]
Thanks for the report. Interesting behavior, specially since I can't find where the ``__file__`` variable is overwritten in the current code base.

**Comment by matus-stehlik** [comment]
@fabianp , the variable is not overwritten, but rather is not set. Given script doesn't run as file (or module), it is read, compiled and executed by following 2 lines in [memory_profiler.exec_with_profiler](https://github.com/pythonprofilers/memory_profiler/blob/95300297e2023f6a3f50f9b016516699a1a95dc9/memory_profiler.py#L1119)


            with open(filename) as f:
                exec(compile(f.read(), filename, 'exec'), ns, ns)

**Comment by Ricocotam** [comment]
It's as easy as doing the same thing as in the line_profiler : [link](https://github.com/rkern/line_profiler/blob/master/kernprof.py#L211)

**Comment by fabianp** [comment]
Could you send a pull request?

**Comment by Ricocotam** [comment]
Ok

**Comment by Ricocotam** [comment]
Done on #230

**Comment by Ricocotam** [comment]
If anyone still has issue, say it here, I think we can close it now.

**Comment by fabianp** [comment]
Closing this one. Thanks @Ricocotam for submitting the fix!
