### ISSUE TITLE
Does it monitor memory usage on GPU from TensorFlow python script?

### ISSUE THREAD

**Issue by tonyreina** [pythonprofilers/memory_profiler#200]
Can I use mprof to monitor the amount of GPU RAM being used by my TensorFlow python script? Or will it only monitor the CPU RAM?

Thanks.
-Tony

**Comment by fabianp** [comment]
It doesn't monitor GPU memory, unless the GPU memory is copied back to main
memory, which it often is but depends on the program

**Comment by tonyreina** [comment]
Thanks!
