### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by majthehero** [pythonprofilers/memory_profiler#204]
Currently I can't use the mprof script.
It fails because there is a space (' ') in the shebang ("C:\Program Files\...").
I googled what to do in that case, but nothing worked - I tried putting the path in quotes, double quotes, removing it completely, etc.

**Comment by Juanlu001** [comment]
Hi @majthehero, would you please try installing the latest development version? We fixed this issue a day ago.

```
pip install https://github.com/pythonprofilers/memory_profiler/archive/master.zip
```

**Comment by majthehero** [comment]
Great, I'll try it tomorrow.
Thanks for the reply.

**Comment by majthehero** [comment]
Everything works, thanks.
