### ISSUE TITLE
%memit jupiter notebook extension option not working

### ISSUE THREAD

**Issue by kkew3** [pythonprofilers/memory_profiler#212]
> Platform: macOS (version `10.13.6 (17G65)`)
> Python version: `3.6.5`
> Jupyter version: `4.4.0`

```python
# profile this cell by running it _once_
%%memit -r 1
print('hello')
```

yields

```plain
hello
hello
hello
hello
hello
hello
hello
peak memory: 164.42 MiB, increment: 0.00 MiB
```

However, it states from documentation (`memit?` in jupyter notebook) that:

> Options:
> -r<R>: repeat the loop iteration <R> times and take the best result.
> Default: 1

This causes problem when the snippet to profile takes long time to execute and so I only wish to run it once.

**Comment by fabianp** [comment]
Pull requests welcome

**Comment by pydevsci** [comment]
Well,  I had a cursory look, but I cannot really see the problem as easily as I wish I could to contribute a pull for you. Either way it is a great tool and thanks for creating it :)

**Comment by leguyader** [comment]
I encountered the problem as well today:

```(base) ❯ ipython3
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext memory_profiler

In [2]: %%memit
   ...: print('hello')
   ...:
   ...:
hello
hello
hello
hello
hello
hello
hello
peak memory: 40.53 MiB, increment: 0.25 MiB

In [3]:
```

I don't understand where this comes from, but looking around similar issue was reported for timeit running 7 times:
[https://stackoverflow.com/questions/50891288/why-does-the-ipython-magic-function-timeit-n1-code-block-execute-code-block](https://stackoverflow.com/questions/50891288/why-does-the-ipython-magic-function-timeit-n1-code-block-execute-code-block)

**Comment by leguyader** [comment]
Line 1069 of memory_profiler.py, adding max_iterations=1 to the memory_usage() call apparently solves the issue.

**Comment by cenzwong** [comment]
![image](https://user-images.githubusercontent.com/44856918/154078900-e5cbf280-b6c4-4bd7-ac2c-09a6b3280e36.png)

I encounter the same problem as well, I have specify -r1, but still the code run three times
