### ISSUE TITLE
The first example in readme not working correctly

### ISSUE THREAD

**Issue by axil** [pythonprofilers/memory_profiler#249]
Here's what I get on both windows and linux. 
```
Line #    Mem usage    Increment   Line Contents
================================================
     1   37.754 MiB   37.754 MiB   @profile
     2                             def my_func():
     3   45.195 MiB    7.441 MiB       a = [1] * (10 ** 6)
     4  197.820 MiB  152.625 MiB       b = [2] * (2 * 10 ** 7)
     5   45.449 MiB    0.000 MiB       del b
     6   45.449 MiB    0.000 MiB       return a
```
I would expect it to show released memory after `del b` as it is described in the readme file.

**Comment by jasonqiao36** [comment]
meet this event too.
on Python3.7.4 Linux

**Comment by Babarberousse** [comment]
Looks like this comes from this commit:
https://github.com/pythonprofilers/memory_profiler/pull/202/commits/5fe38da926738a7715c860053a498859e2db0c87

Which solved this issue:
https://github.com/pythonprofilers/memory_profiler/issues/195

The increment cannot be negative anymore and is not the sum of all the increments on this line. It is the biggest increment that occured for this line (or 0 if no increment).

If you want to monitor freed memory you can still look at the `Mem usage` column. You could also roll back to a version <= 0.54 if you want the old table.

I also feel like the old table was more intuitive, although it may be useful to add the line occurence count to reduce confusion with loops. This would also help: https://github.com/pythonprofilers/memory_profiler/issues/272

@fabianp : I can implement this last solution if you are okay with it.

**Comment by fabianp** [comment]
Yes, please do
