### ISSUE TITLE
how to use the flame option for mprof plot?

### ISSUE THREAD

**Issue by idevz** [pythonprofilers/memory_profiler#257]
when I exec the `mprof plot --flame` command following README, I got this error:

```bash
(py36) > $ mprof plot --flame   
usage: mprof plot [options] [file.dat]
mprof: error: unrecognized arguments: --flame
```

the information about this tool:
```bash
(py36) > $ pip show memory_profiler            
Name: memory-profiler
Version: 0.55.0
Summary: A module for monitoring memory usage of a python program
Home-page: http://pypi.python.org/pypi/memory_profiler
Author: Fabian Pedregosa
Author-email: f@bianp.net
License: BSD
Location: /.../py36/lib/python3.6/site-packages
Requires: psutil
Required-by:
```

does the `--flame` option is still alive?

**Comment by fabianp** [comment]
Thanks for the report. I believe it's just that the version on pypi is old, I made a new release that should have this option. Please update from pypi and try again

**Comment by idevz** [comment]
@fabianp thank a lot, the option is ok now, but the output file is still a png file, how can I get the function and timestamp names  on hover? Am I miss some details?
