### ISSUE TITLE
Breaking change in `memory_usage` return value in 0.56.0

### ISSUE THREAD

**Issue by Flid** [pythonprofilers/memory_profiler#258]
Some code has stopped working on our side a few days ago, and we tracked it down to:

```python 
from memory_profiler import memory_usage
print(memory_usage(lambda: None, interval=0.1, timeout=1, max_usage=True, retval=1, include_children=True))
```
returning `([17.82421875], None)` in 0.55.0, but `(18.6640625, None)` in 0.56.0.

**Comment by fesaille** [comment]
This could explain that `%memit` is broken in jupyter notebook

```python
/opt/conda/lib/python3.7/site-packages/memory_profiler.py in memit(self, line, cell)
   1053                                max_usage=True,
   1054                                include_children=include_children)
-> 1055             mem_usage.append(tmp[0])
   1056 
   1057         result = MemitResult(mem_usage, baseline, repeat, timeout, interval,

TypeError: 'float' object is not subscriptable
```

**Comment by fabianp** [comment]
Thanks for the report. Pull requests are welcome to fix this issue

**Comment by fabianp** [comment]
in the meantime I deleted 0.56 from pypi

**Comment by gruenerBlitz** [comment]
1ecaf4edae1d84684dcc560df1e798aa7ed9a46d is pretty explicit about this change:
> **Unpacking return value if max_usage is True**
> If the memory_usage function is called with (callable, arglist, kwargs), as target and max_usage is True, the function now returns a number instead of a list with one entry.

**Comment by jnothman** [comment]
1. conda-forge still serves memory_profiler 0.56
2. The break to memit is pretty disruptive. memit doesn't appear to have any testing.
