### ISSUE TITLE
memory_usage reruns the function if the function runs faster than time interval

### ISSUE THREAD

**Issue by akirakotsugai** [pythonprofilers/memory_profiler#279]
when I use the memory_usage function, if the given time interval is smaller than the time the monitored function takes to run, it reruns the function as many time as necessary to meet the time interval. Has anybody had it before? my quick fix was make sure the monitored function is slower than the time interval by using time.sleep. Is there a better solution?

**Comment by patrickpei** [comment]
Pass in `max_iterations=1`. On a related note, could this please not be the default behavior? It can be confusing why profiling a function runs it multiple times at an internally decided execution time cutoff ([0.5 seconds](https://github.com/pythonprofilers/memory_profiler/blob/master/memory_profiler.py#L361))
