### ISSUE TITLE
Feature Request: Issue Markers Delimiting Code Regions in .dat

### ISSUE THREAD

**Issue by william-silversmith** [pythonprofilers/memory_profiler#310]
When profiling a more complex setup, it can be difficult to determine which part of the code is contributing to the memory usage. One trick that I sometimes use is use `time.sleep` for an extended period so I can see some kind of regional delimiter between different parts of the code.

However, it would be very handy if one could write something like this:

```
import memory_profiler

setup_experiment()

memory_profiler.start_region("forloop")
for i in range(100000000):
   # something expensive
memory_profiler.end_region("forloop")
```

This would inject tokens indicating the start and end of the code region into the `.dat` which could then be used to automatically shade the plot like I have done manually here:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/2517065/114072717-91836a80-9870-11eb-93a9-707855e1a062.png">

**Comment by peterjc** [comment]
Your idea would work equally well for my needs - I was looking for a light weight alternative to the ``@profile`` decorator, something like ``@profile(backend=False)`` or just ``@label`` which would just capture the start/end time for that method and use it to label the final graph - but without the overhead of looking at the extra details within that method.

**Comment by william-silversmith** [comment]
I figured out that function timestamping does something very similar to this idea and is documented in the readme. It suits my purposes.

**Comment by peterjc** [comment]
@william-silversmith could you expand on that comment slightly please? I don't see any mention of ``timestamping`` within https://github.com/pythonprofilers/memory_profiler/blob/master/README.rst

Are you just adding some well placed ``@profile`` decorators to your functions/methods?

**Comment by william-silversmith** [comment]
Yes that's what I ended up doing
