### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by 0phoff** [pythonprofilers/memory_profiler#338]
Sorry to open an issue for this, but I found no information on when you release new versions.
The current pypi/conda version is over a year old and is 30 commits behind this master branch.

The reason I am asking is because I want to use `psutil_uss`, but it is annoying to need to install this package from github for every virtual environment I create! :)

Thanks for the amazing effort with this package.

**Comment by fabianp** [comment]
wow, time flies! just made a new release: https://pypi.org/project/memory-profiler/0.59.0/
