### ISSUE TITLE
I'm a beginner in the world of developing, I just finished learning python and html and css what's the next step please?I need a help with that.

### ISSUE THREAD

**Issue by Ocstanley29** [pythonprofilers/memory_profiler#392]

**Comment by ashis-paul-blox** [comment]
Next step is not opening meaningless issues on an open source project maybe?

**Comment by altendky** [comment]
No need to be rude, but I agree this isn't applicable to this project.  I personally learned a lot reading, asking questions, and helping answer questions in the Python IRC channel.  https://www.python.org/community/irc/
