### ISSUE TITLE
Memory usage does not work with class methods?

### ISSUE THREAD

**Issue by rominf** [pythonprofilers/memory_profiler#47]
I want to profile time and memory usage of class method. 
When I try to use `partial` from `functools` I got this error:

```
File "/usr/lib/python2.7/site-packages/memory_profiler.py", line 126, in memory_usage
  aspec = inspect.getargspec(f)
File "/usr/lib64/python2.7/inspect.py", line 815, in getargspec
  raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <functools.partial object at 0x252da48> is not a Python function
```

By the way exactly the same approach works fine with `timeit` function.

When I try to use `lambda` as was I got this error:

```
File "/usr/lib/python2.7/site-packages/memory_profiler.py", line 141, in memory_usage
  ret = parent_conn.recv()
IOError: [Errno 4] Interrupted system call
```

How can I handle class methods with memory_profiler? Are there any (even dirty) ways?

I asked this question on SO: http://stackoverflow.com/questions/16593246/how-to-use-memory-profiler-python-module-with-class-methods

UPD: fixed broken link to SO

**Comment by Juanlu001** [comment]
This is missing a [SSCCE](http://www.sscce.org/).
