### ISSUE TITLE
Reported memory usage is sometimes wrong.

### ISSUE THREAD

**Issue by pgervais** [pythonprofilers/memory_profiler#52]
In some cases, memory is not reclaimed because of memory profiler. Here's a small example exhibiting the problem:

``` python
Line #    Mem usage    Increment   Line Contents
================================================
     6                             @profile
     7    20.254 MB     0.000 MB   def random_array(shape):
     8    43.148 MB    22.895 MB       arr1 = np.random.randn(*shape)
     9   138.320 MB    95.172 MB       arr = scipy.signal.detrend(arr1, axis=1)
    10   138.320 MB     0.000 MB       del arr1
    11   138.320 MB     0.000 MB       gc.collect()
    12                             
    13   138.320 MB     0.000 MB       col_mean = np.mean(arr, axis=1)
    14   138.320 MB     0.000 MB       np.testing.assert_array_less(abs(col_mean), 1e-15)
    15   138.320 MB     0.000 MB       return arr
```

`arr1` is a numpy array weighting 22.9MB. Detrending creates an array that has exactly the same size (`arr`), but memory usage increases by 95MB, and does not go down, even after line 10.

I have checked that this is a side-effect of the memory_profiler module, by monitoring global memory usage, without using memory_profiler at all. Memory usage does raise to 96MB during execution of scipy.signal.detrend, but also does decrease just after it execution.

memory_profiler might be keeping a reference to the `arr1` array somehow, but I wasn't able to find how even with guppy/heapy (which complains somehow when memory_profiler is loaded). 

This seems to me like a tricky issue, but it is really important, since reported memory usage can be completely different than the value obtained without profiling.

EDIT: here is a snapshot of the memory usage graph.

![example](https://f.cloud.github.com/assets/3764624/788839/ec6da73e-eb04-11e2-85b9-a83976f50c9f.png)

**Comment by jbschiratti** [comment]
I used `memory-profiler` today and noticed the same behavior.

I'm using:

- python 3.8.3
- numpy 1.19.4
- scipy 1.6.2
- memory-profiler 0.58.0

The code: 
```python
import gc

import numpy as np
from memory_profiler import profile
from scipy.signal import detrend


@profile
def random_array(shape):
    arr1 = np.random.randn(*shape)
    arr = detrend(arr1, axis=1)

    del arr1
    gc.collect()

    col_mean = np.mean(arr, axis=1)
    np.testing.assert_array_less(abs(col_mean), 1e-15)
    return arr


if __name__ == '__main__':

    random_array((1000, 1000))

```

The output:

```
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
     8     81.5 MiB     81.5 MiB           1   @profile
     9                                         def random_array(shape):
    10     89.1 MiB      7.7 MiB           1       arr1 = np.random.randn(*shape)
    11    128.9 MiB     39.8 MiB           1       arr = detrend(arr1, axis=1)
    12                                         
    13    128.9 MiB      0.0 MiB           1       del arr1
    14    128.9 MiB      0.0 MiB           1       gc.collect()
    15                                         
    16    128.9 MiB      0.0 MiB           1       col_mean = np.mean(arr, axis=1)
    17    128.9 MiB      0.0 MiB           1       np.testing.assert_array_less(abs(col_mean), 1e-15)
    18    128.9 MiB      0.0 MiB           1       return arr
```

It seems that `del arr1` has no effect on the memory usage.
