### ISSUE TITLE
DeprecationWarning: get_memory_info() is deprecated; use memory_info() instead

### ISSUE THREAD

**Issue by oeddyo** [pythonprofilers/memory_profiler#79]
Anybody found this warning? 

Can't even suppress by
-W ignore

I guess this is because psutil changed the function from get_memory_info to memory_info

**Comment by Juanlu001** [comment]
As https://github.com/pythonprofilers/memory_profiler/issues/94 was closed, perhaps this is not the case anymore?

**Comment by Juanlu001** [comment]
Closing this, feel free to reopen if the problem appears again.
